runtime: python312 # Using python312 as a recent, stable version supported by GAE
instance_class: F1
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app # Standard for FastAPI on GAE
automatic_scaling:
  min_instances: 0 # Enables scale to zero for cost-effectiveness

env_variables:
  PYTHON_ ympäristö: "production" # Example environment variable

handlers:
- url: /.*
  script: auto

# Note: Consider adding health checks for better reliability in a production setup.
# health_check:
#   enable_health_check: True
#   check_interval_sec: 300
#   timeout_sec: 4
#   unhealthy_threshold: 2
#   healthy_threshold: 2
#   restart_threshold: 2 # Number of consecutive failed checks before restarting
#   # script: "/liveness_check" # Path to your liveness check endpoint

# Note: Ensure to list any necessary libraries that need to be installed via C extensions
# or other system packages under the 'libraries' section if required,
# though for standard Python packages, requirements.txt is the primary method.
# libraries:
# - name: "some_c_library"
#   version: "latest"
